
name: GitHub Security Alerts for Jira

on:
  workflow_dispatch
jobs:
  syncSecurityAlerts:
    runs-on: ubuntu-latest
    steps:
      - name: "Sync security alerts to Jira issues"
        uses: reload/github-security-jira@v1.x
        env:
          GH_SECURITY_TOKEN: ${{ secrets.PAT_TOKEN }}
      - name: Jira Integration
        env:
          GH_SECURITY_TOKEN: ${{ secrets.PAT_TOKEN }}
          JIRA_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
        run: |
           jira_ticket() {
           cat <<- EOF
            {
           "fields":{
           "project":{
           "key":"TS"
           },
           "summary":"${{ github.actor }} alert from $GITHUB_REPOSITORY",
           "description":"Further details of the alert can be seen here $advisory_description",
           "assignee":{
           "name":"Keert2"
           },
           "issuetype":{
           "name":"Incident"
           },
           "priority":{
           "name":"Low"
           },
           "labels":[
           "Dependabot"
           ]
           } 
           }
           EOF
           } 
             curl -sH "Authorization: Bearer ${JIRA_TOKEN}" -X POST --data "$(jira_ticket)" \
                             -H "Content-Type: application/json" https://keerthanatest.atlassian.net
          
        shell: bash
