
name: fetch my metadata
on: pull_request

permissions:
  pull-requests: write
  contents: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'keerthana2022'}}
    steps: 
      - name: get values 
        run: |
             number=`curl -s https://api.github.com/search/issues?q=sha:${{ github.event.pull_request.head.sha }} | grep "number" | cut -d ":" -f 2| cut -c 2`
             echo $number
             url=`https://github.com/$GITHUB_REPOSITORY/security/dependabot/$number`
             echo $url
        shell: bash
